version: '3.8'

services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "15432:5432" 
    networks:
      - postgres-compose-network
    restart: always
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PW}
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network
    restart: always

networks: 
  postgres-compose-network:
    driver: bridge